### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by AlokenC** [anushaven/CSCI3308-Team1-SnowSpices#12]
A page that displays the User's information, tags, address, email, name, etc.. This page will also allow for the user to update their information with a post request

**Comment by AlokenC** [comment]
The visual components of the profile page are close to completion. Further visual attributes will be added after testing is conducted that confirms that data from the login page is being queried and used in the profile page.

**Comment by anushaven** [comment]
Made some changes to route in index so variables are accessing intended data.
