### ISSUE TITLE
register.ejs

### ISSUE THREAD

**Issue by ecars42** [anushaven/CSCI3308-Team1-SnowSpices#15]
This is the updating of the first few ejs files but specifically the register page. We needed to adapt the lab 9 register to include all the filter categories that we want to search our data for.

**Comment by ecars42** [comment]
Register page has correct entry fields. Having issues with required entry for email in the field. Need to figure out submission function on register.ejs by next week

**Comment by McChicken78** [comment]
I did the register.ejs and made it so the data you input is input correctly into the tables. Did this by updating the index.js files, along with updating the sql files so that the data matched up.
